# Generated by Django 5.0.6 on 2024-06-12 09:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=2000, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Tėvinė kategorija',
                'verbose_name_plural': 'Tėvinės kategorijos',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=2000, verbose_name='Aprašymas')),
                ('image', models.ImageField(blank=True, upload_to='images/article/%Y/%m/%d/', verbose_name='Nuotrauka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category', verbose_name='Tėvinė kategorija')),
            ],
            options={
                'verbose_name': 'Vaikinė kategorija',
                'verbose_name_plural': 'Vaikinės kategorijos',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('short_description', models.TextField(blank=True, max_length=2000, verbose_name='Trumpas aprašymas')),
                ('full_description', tinymce.models.HTMLField(blank=True, verbose_name='Pilnas aprašymas')),
                ('image', models.ImageField(blank=True, upload_to='images/article/%Y/%m/%d/', verbose_name='Nuotrauka')),
                ('status', models.CharField(choices=[('published', 'Paskelbta'), ('hidden', 'Paslėpta')], default='published', max_length=10, verbose_name='Statusas')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autorius')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_posts', to=settings.AUTH_USER_MODEL, verbose_name='Atnaujino')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.subcategory', verbose_name='Subkategorija')),
            ],
            options={
                'verbose_name': 'Straipsnis',
                'verbose_name_plural': 'Straipsniai',
                'indexes': [models.Index(fields=['status'], name='blog_articl_status_57fc64_idx')],
            },
        ),
    ]
